<?php

use App\Models\Brand;
use Illuminate\Database\Seeder;

class BrandTableSeeder extends Seeder
{
    public $brands = Array(
        "FORD",
        "CHEVROLETTE",
        "CHRYSLER",
        "CATERPILLAR",
        "MERCURY",
        "D100",
        "JEEP",
        "ISUZU",
        "HONDA",
        "TOYOTA",
        "DAIHATSU",
        "FIAT",
        "KODIAK",
        "DAEWOO",
        "SEAT",
        "LADA",
        "NISSAN",
        "RANGE",
        "MAZDA",
        "KIA",
        "REGNAULT",
        "KANO",
        "PEGASO",
        "IVECO",
        "PLYMOUNTH",
        "HYUNDAI",
        "EBRO",
        "SUZUKI",
        "MERCEDES BENZ",
        "MACK",
        "TITAN",
        "CADILLAC",
        "MITSUBISCHI",
        "VOLKSWAGEN",
        "ACADIAN",
        "LAND ROVER",
        "YAMAHA",
        "HILLAMN",
        "ENCABA",
        "COMMER",
        "PONTIAC",
        "CHANGHE",
        "SAAB",
        "CHANA",
        "GEELY",
        "REMYVECA",
        "CHERY",
        "YASUKY",
        "UNICO",
        "SHINERAY",
        "DACIA",
        "CARIBE",
        "JAC",
        "INTERNACIONAL",
        "PEUGEOT",
        "HUONIAO",
        "FREIGHTLINER",
        "VENIRAUTO",
        "CHUTO",
        "GREAT WALL",
        "WHITE",
        "CITROEN",
        "SAIC",
        "ALFA ROMEO",
        "BERA",
        "VOLVO",
        "QINGQI",
        "ROSSETTI",
        "FABR. EXTRANGERA",
        "HORSE",
        "TATA",
        "CONCORD",
        "KEEWAY",
        "JMC",
        "DONGFENG",
        "ROVER",
        "HAFEI",
        "ZOTYE",
        "HFC1061K",
        "FOTON",
        "BUICK",
        "LINCOLN",
        "MANAURE",
        "HATCH BACK",
        "GWM",
        "DODGE",
        "MASTRO",
        "INBUS",
        "ORINOCO",
        "LUBEROWI",
        "G.M.C",
        "BMW",
        "WANGYE",
        "HAOJIANG",
        "SUBARU",
        "BATEAS",
        "INPRODI",
        "RODO LINEA",
        "kawasaki",
        "HINO",
        "OPEL",
        "LEXUS",
        "MD HAOJIN",
        "YUEXIN",
        "HASTRO",
        "SUKIDA",
        "carrocerias atlas",
        "MD",
        "FAVOLCAR",
        "FABRICACION NAC",
        "SPILFER",
        "SKYGO",
        "YINGANG",
        "UNITED MOTORS",
        "FYM",
        "AVA",
        "BENELLI",
        "FORTA GOLDEN DRAGON",
        "AVILA",
        "ENDURO",
        "loncin",
        "SANYA",
        "FURGO ESTACAS",
        "skoda",
        "DONGBEN",
        "OLDSMOBILE",
        "EMPIRE",
        "HAOJUE",
        "CHASIS",
        "CHASIS 60160",
        "NEW LEON",
        "MOTO MARKET",
        "zuzuki",
        "TUNING",
        "KTC",
        "QIPAI",
        "HUALONG",
        "YAMAZAKI",
        "ZXMCO",
        "KINGTON LIYANG",
        "ROFERCA MOTOR",
        "AUTOGAGO",
        "ANDINO",
        "AUTOGAGO",
        "UTILITY",
        "INVERMETAL",
        "NEW JAGUAR",
        "RENAULT",
        "YUTONG BUS",
        "TINTAN",
        "XTZ250",
        "GREAT WALL",
        "VENTO",
        "QUE MOTO",
        "YUTONG BUS",
        "MITSUBISHI",
        "GIUSEMI",
        "UNIVERS",
        "YAMAHA",
        "RKV",
        "ASTRA",
        "HORSE KW-150"
    );
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        foreach ($this->brands as $key => $brand) {
            Brand::create([
                'name' => $brand
            ]);
        }
    }
}
